plugins:
    versioned_plugin:
        executor: host_agent
        package_name: versioned-plugin
        package_version: 0.0.1
        source: null
        install: true

node_types:
  cloudify.versioned.nodes.File:
    derived_from: cloudify.nodes.Root
    properties:
      path:
        description: >
            Where the test file should be created.
            The instance ID will be appended to this.
            e.g. /tmp/versioned_plugin_test_file_nodename_a123ff
        default: /tmp/versioned_plugin_test_file
      content:
        description: What the contents of the test file should be.
        default: This is a test file.
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versioned_plugin.versioned_plugin.file.create
          inputs: {}
        delete:
          implementation: versioned_plugin.versioned_plugin.file.delete
          inputs: {}

  cloudify.versioned.nodes.Wait:
    derived_from: cloudify.nodes.Root
    properties:
      delay:
        description: How long to wait for, in seconds.
        default: 60
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: versioned_plugin.versioned_plugin.wait.wait
